################################################################################
# WiFi Common Component for ESP32
################################################################################
# Tutorial:     https://youtu.be/
# Reference(s): https://docs.espressif.com/projects/arduino-esp32/en/latest/boards/ESP32-C3-DevKitM-1.html
# ------------------------------------------------------------------------------  
# Usage:
#   Add the following code to package section in the device file
# ------------------------------------------------------------------------------
# packages:
#   board: !include common/network/wifi.yaml
# ------------------------------------------------------------------------------
# Notes:
#     - Uses the following substitutions from the project file:
#       - device_internal_name
#       - device_sampling_time
#       - device_ip_address
#     - Uses the following from the secrets file:
#       - wifi_ssid
#       - wifi_password
#       - gateway_address
#       - subnet_address
#       - dns_address (optional)
#       - ap_password
# ------------------------------------------------------------------------------     
# Author: Pascal Parent
# Company: Home Automator (ZA)
# Web: https://www.youtube.com/@homeautomatorza
# Version: 1.0.0
# Licence: CCO 1.0 https://creativecommons.org/publicdomain/zero/1.0/
# ------------------------------------------------------------------------------
# WARNING:
# This code carries a "It works on my setup" disclaimer!
# Use at your own risks!
################################################################################

# ------------------------------------------------------------------------------
# WiFi Settings
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  manual_ip:
    static_ip: ${device_ip_address}
    gateway: !secret gateway_address
    subnet: !secret subnet_address
  domain: .local # Network domain name.
  fast_connect: true # Reconnect with the last access point without searching.
  ap: # Enable fallback hotspot (captive portal) in case wifi connection fails.
    ssid: ${device_wifi_name}
    password: !secret ap_password

captive_portal:

# ------------------------------------------------------------------------------
# Sensors
sensor:
  - platform: wifi_signal
    id: ${device_internal_name}_wifi_signal_db
    name: WiFi Signal dB
    icon: mdi:wifi
    update_interval: ${device_sampling_time}
    entity_category: diagnostic
    disabled_by_default: true

# ------------------------------------------------------------------------------
# Text Sensors
text_sensor:
  # WiFi internal sensors
  - platform: wifi_info
    ip_address:
      id: ${device_internal_name}_ip_address
      name: IP Address
      icon: mdi:ip-network
    ssid:
      id: ${device_internal_name}_connected_ssid
      name: Connected SSID
      icon: mdi:access-point
    mac_address:
      id: ${device_internal_name}_mac_address
      name: Mac Wifi Address
      icon: mdi:network-outline
      disabled_by_default: true
    dns_address:
      id: ${device_internal_name}_dns_address
      name: DNS Address
      icon: mdi:dns
      disabled_by_default: true
